version: '3.8'

services:
  web:
    image : hugohlr/oc_lettings_site:${COMMIT_SHA}
    build: 
      context: .
      args:
        - SECRET_KEY=${SECRET_KEY}
    env_file: ./.env
    ports:
      - "8000:8000"