# Generated by Django 3.0 on 2024-03-13 16:03

from django.db import migrations

def transfer_lettings_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('lettings', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')

    for old_address in OldAddress.objects.all():
        new_address = NewAddress.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )

        for old_letting in OldLetting.objects.filter(address=old_address):
            NewLetting.objects.create(
                title=old_letting.title,
                address=new_address
            )

def backward_transfer_lettings_data(apps, schema_editor):
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')

    for new_letting in NewLetting.objects.all():
        old_address = OldAddress.objects.create(
            number=new_letting.address.number,
            street=new_letting.address.street,
            city=new_letting.address.city,
            state=new_letting.address.state,
            zip_code=new_letting.address.zip_code,
            country_iso_code=new_letting.address.country_iso_code
        )
        OldLetting.objects.create(
            title=new_letting.title,
            address=old_address
        )
        new_letting.address.delete()

    NewAddress.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_lettings_data, backward_transfer_lettings_data),
    ]

