# Generated by Django 3.0 on 2024-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20240313_1645'),
        ('profiles', '0002_auto_20240313_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
